export const POIS = [
  {
    id: 'ando-center',
    lat: 36.3275, lng: 138.4267,
    title: '安藤百福センター',
    titleEn: 'Momofuku Ando Center',
    desc: 'Outdoor youth training facility founded by the inventor of instant ramen.',
    history: 'Established in 2010 by the Nissin Foods founder Momofuku Ando\'s foundation. The center sits on a forested hillside and was designed to inspire creativity and self-reliance in young people through outdoor activities. Ando believed that the same spirit of invention that led him to create instant noodles could be nurtured through nature.',
    funFact: 'Momofuku Ando invented instant ramen at age 48 after going bankrupt. He ate chicken ramen every day for the rest of his life and lived to 96.',
    year: 2010,
    color: '#e74c3c',
    related: ['komoro-castle', 'manns-wine'],
    wiki: 'Momofuku_Ando',
  },
  {
    id: 'komoro-castle',
    lat: 36.3270, lng: 138.4190,
    title: '小諸城址 懐古園',
    titleEn: 'Komoro Castle (Kaikoen Park)',
    desc: 'Rare "hole castle" built lower than the surrounding town.',
    history: 'Constructed around 1490 by the Ōi clan, Komoro Castle is unusual because it sits in a valley below the castle town — an "anajo" (穴城). The stone walls were reinforced by Sengoku Tadamasa after the Battle of Sekigahara in 1600. During the Meiji Restoration, the castle was decommissioned and converted into Kaikoen Park in 1926.',
    funFact: 'Most Japanese castles sit on hilltops. Komoro Castle was built in a natural ravine, making it one of the few "hole castles" where you literally walk downhill to enter.',
    year: 1490,
    color: '#f39c12',
    related: ['toson-museum', 'komoro-station', 'chikuma-river'],
    wiki: 'Komoro_Castle',
  },
  {
    id: 'komoro-station',
    lat: 36.3260, lng: 138.4180,
    title: '小諸駅',
    titleEn: 'Komoro Station',
    desc: 'Historic railway station connecting Komoro to the Shinano line.',
    history: 'Opened in 1888 as part of the Shinetsu Main Line, Komoro Station became a vital link between Nagano and the rest of Japan. The Shinano Railway took over local operations in 1997 when the Hokuriku Shinkansen bypassed the old route through the mountains.',
    funFact: 'The station is so close to Komoro Castle that you can see the ancient stone walls from the platform — feudal history meets modern transit.',
    year: 1888,
    color: '#2ecc71',
    related: ['komoro-castle', 'toson-museum'],
    wiki: 'Komoro_Station',
  },
  {
    id: 'nunobiki',
    lat: 36.3395, lng: 138.4295,
    title: '布引観音',
    titleEn: 'Nunobiki Kannon Temple',
    desc: 'Dramatic cliffside temple built into the rock face above a gorge.',
    history: 'According to legend, the temple was founded in 724 AD during the Nara period. The main hall (Kannon-dō) is wedged into a cliff face above the Chikuma River gorge — a style called "kake-zukuri" (hanging construction), similar to Kiyomizu-dera in Kyoto. The temple enshrines a Kannon statue said to have miraculous powers.',
    funFact: 'Legend says a poor farmer\'s cow dragged a cloth up the mountain, leading him to the Kannon statue. The name "Nunobiki" literally means "cloth pulling."',
    year: 724,
    color: '#9b59b6',
    related: ['komoro-castle', 'chikuma-river'],
    wiki: 'Nunobiki_Kannon',
  },
  {
    id: 'toson-museum',
    lat: 36.3215, lng: 138.4155,
    title: '藤村記念館',
    titleEn: 'Shimazaki Toson Museum',
    desc: 'Museum honoring the great Meiji-era novelist and poet.',
    history: 'Shimazaki Toson (1872–1943) lived in Komoro from 1899 to 1905 while teaching at a local school. During this time he wrote "Chikumagawa no Sketch" (Sketches of the Chikuma River), a beloved collection of nature essays. The museum preserves his study, manuscripts, and personal effects.',
    funFact: 'Toson was so broke when he arrived in Komoro that he taught English at a girls\' school for ¥15/month. His Komoro writings are now required reading in Japanese schools.',
    year: 1899,
    color: '#1abc9c',
    related: ['komoro-castle', 'komoro-station', 'chikuma-river'],
    wiki: 'Tōson_Shimazaki',
  },
  {
    id: 'manns-wine',
    lat: 36.3310, lng: 138.4350,
    title: 'マンズワイン小諸',
    titleEn: 'Manns Wine Komoro Winery',
    desc: 'One of Japan\'s oldest wineries, producing wine since the 1960s.',
    history: 'Founded in 1962 by Kikkoman Corporation, Manns Wine chose Komoro for its high altitude (700m), volcanic soil from Mount Asama, and dramatic temperature swings — conditions similar to premium wine regions. The winery pioneered Japanese Merlot and Chardonnay production.',
    funFact: 'Yes, that Kikkoman — the soy sauce company. They figured if they could ferment soybeans, why not grapes?',
    year: 1962,
    color: '#e91e63',
    related: ['ando-center', 'asama'],
    wiki: 'Japanese_wine',
  },
  {
    id: 'chikuma-river',
    lat: 36.3240, lng: 138.4230,
    title: '千曲川',
    titleEn: 'Chikuma River',
    desc: 'The longest river in Japan, carving through the Komoro valley.',
    history: 'The Chikuma River (which becomes the Shinano River downstream) has shaped Komoro\'s landscape for millennia. The catastrophic flood of 1742 (Kan\'pō flood) killed hundreds and reshaped the entire valley floor. The river\'s deep gorge near Komoro Castle creates the dramatic cliff scenery the area is known for.',
    funFact: 'At 367km, the Shinano/Chikuma is Japan\'s longest river. Shimazaki Toson was so obsessed with it he named his most famous book after it.',
    year: 1742,
    color: '#3498db',
    related: ['komoro-castle', 'nunobiki', 'toson-museum'],
    wiki: 'Shinano_River',
  },
  {
    id: 'asama',
    lat: 36.4060, lng: 138.5230,
    title: '浅間山',
    titleEn: 'Mount Asama',
    desc: 'One of Japan\'s most active volcanoes, towering over Komoro.',
    history: 'Mount Asama (2,568m) has erupted repeatedly throughout history. The devastating 1783 eruption (Tenmei eruption) sent pyroclastic flows into Kambara village, killing over 1,500 people and causing crop failures across Japan. The volcanic soil it deposited is what makes Komoro\'s agriculture and wine production possible today.',
    funFact: 'The 1783 eruption was so massive it may have contributed to unusual weather in Europe, compounding the conditions that led to the French Revolution six years later.',
    year: 1783,
    color: '#ff5722',
    related: ['manns-wine', 'chikuma-river'],
    wiki: 'Mount_Asama',
  },
  // === Kori Fuketsu / Eastern direction POIs ===
  {
    id: 'kori-fuketsu',
    lat: 36.3410, lng: 138.4580,
    title: '氷風穴',
    titleEn: 'Kori Fuketsu Ice Wind Cave',
    desc: 'Natural wind caves used as refrigeration since the Meiji era.',
    history: 'The Kori Fuketsu caves are natural rock crevices where cold air circulates year-round, maintaining temperatures near 0°C even in summer. During the Meiji era (1870s–1910s), the caves were used commercially to store silkworm eggs at precise temperatures, which was critical for Japan\'s booming silk industry. At their peak, these caves stored eggs for the entire Nagano prefecture silk trade.',
    funFact: 'These caves are literally nature\'s refrigerator — they stay near freezing in August when it\'s 35°C outside. The locals called them "the town freezer" centuries before electricity existed.',
    year: 1870,
    color: '#00BCD4',
    related: ['takamine', 'onio-pass', 'asama'],
    wiki: 'Komoro,_Nagano',
  },
  {
    id: 'takamine',
    lat: 36.3520, lng: 138.4680,
    title: '高峰高原',
    titleEn: 'Takamine Kogen Highlands',
    desc: 'Alpine plateau at 2,000m with panoramic views of the Japanese Alps.',
    history: 'The Takamine highlands have been used as summer grazing land for centuries. In the modern era, they became a popular hiking and skiing destination. The area is part of the Jōshin\'etsu-kōgen National Park, established in 1949 to protect the volcanic landscape around Mount Asama.',
    funFact: 'On a clear day from Takamine, you can see Mount Fuji, the Northern Alps, AND the Pacific Ocean side mountains. It\'s basically Japan\'s grandstand seat.',
    year: 1949,
    color: '#8BC34A',
    related: ['asama', 'kori-fuketsu'],
    wiki: 'Jōshin%27etsu-kōgen_National_Park',
  },
  {
    id: 'onio-pass',
    lat: 36.3350, lng: 138.4480,
    title: '追分宿',
    titleEn: 'Oiwake-juku Post Town',
    desc: 'Historic Nakasendo highway post station at a major crossroads.',
    history: 'Oiwake was a crucial junction on the Nakasendo (中山道), one of the five major highways of Edo-period Japan. Here, the Nakasendo and the Hokkoku Kaidō (road to Hokuriku) diverged. The post town thrived from the 1600s–1868 serving daimyo processions and travelers. Many original buildings and the atmosphere of the Edo period remain.',
    funFact: 'The name "Oiwake" means "the parting" — travelers here had to choose their path. It became a metaphor in Japanese poetry for life\'s difficult choices.',
    year: 1602,
    color: '#FF9800',
    related: ['komoro-castle', 'kori-fuketsu', 'komoro-station'],
    wiki: 'Oiwake-juku',
  },
  {
    id: 'manaita',
    lat: 36.3380, lng: 138.4520,
    title: '御牧ヶ原',
    titleEn: 'Mimaki-ga-hara Plateau',
    desc: 'Ancient imperial horse pasture on a volcanic plateau.',
    history: 'Since the Heian period (794–1185), this plateau was designated as an imperial horse ranch (御牧 — mimaki). The court in Kyoto relied on horses from this region for military and ceremonial purposes. The volcanic ash soil from Mount Asama made the grasslands ideal for grazing. Today it\'s known for agriculture — especially lettuce and highland vegetables.',
    funFact: 'The Emperor\'s horses were raised here over 1,000 years ago. Now it grows most of Tokyo\'s fancy restaurant lettuce. From horsepower to salad power.',
    year: 900,
    color: '#795548',
    related: ['kori-fuketsu', 'asama', 'komoro-castle'],
    wiki: 'Komoro,_Nagano',
  },
  // === West of Komoro — toward Ueda / Bessho ===
  {
    id: 'unno-juku',
    lat: 36.3630, lng: 138.3300,
    title: '海野宿',
    titleEn: 'Unno-juku Post Town',
    desc: 'Beautifully preserved Edo-period post town on the Hokkoku Kaidō.',
    history: 'Unno-juku was established in 1625 as a post station on the Hokkoku Kaidō highway connecting Edo to the Japan Sea coast. The town retains over 100 traditional buildings with their characteristic "udatsu" fire walls and lattice windows. After the highway era ended, the town survived by pivoting to silkworm raising — many buildings still have second-floor ventilation windows from that industry.',
    funFact: 'The town is so well preserved that film crews regularly use it for period dramas. Residents joke that they can\'t renovate their houses because a samurai might need to walk past next week.',
    year: 1625,
    color: '#8D6E63',
    related: ['onio-pass', 'komoro-station', 'ueda-castle'],
    wiki: 'Unno-juku',
  },
  {
    id: 'ueda-castle',
    lat: 36.4010, lng: 138.2490,
    title: '上田城',
    titleEn: 'Ueda Castle',
    desc: 'Legendary fortress of the Sanada clan that twice repelled the Tokugawa army.',
    history: 'Built in 1583 by Sanada Masayuki, Ueda Castle is famous for withstanding two sieges by the vastly larger Tokugawa forces — in 1585 and again in 1600 before the Battle of Sekigahara. Despite being a relatively small castle, Sanada\'s brilliant tactical use of the Chikuma River and decoy gates humiliated the Tokugawa twice. The castle was dismantled after the Sanada sided with the losing Toyotomi, but was partially rebuilt by the Sengoku clan (the same family that later held Komoro Castle).',
    funFact: 'Sanada Masayuki beat an army 7 times his size with clever river flooding and fake retreat tactics. The Tokugawa were so embarrassed they tried to erase it from official records.',
    year: 1583,
    color: '#F44336',
    related: ['komoro-castle', 'unno-juku', 'bessho-onsen'],
    wiki: 'Ueda_Castle',
  },
  {
    id: 'bessho-onsen',
    lat: 36.3580, lng: 138.1780,
    title: '別所温泉',
    titleEn: 'Bessho Onsen',
    desc: 'One of Japan\'s oldest hot spring towns, called "Kamakura of Shinano."',
    history: 'Bessho Onsen has been in use since at least the Heian period (794–1185) and is considered one of Japan\'s three oldest hot springs. During the Kamakura period (1185–1333), the area became a cultural center rivaling Kamakura itself — earning it the nickname "Shinano no Kamakura." The Hōjō clan built numerous temples here, several of which contain National Treasures.',
    funFact: 'The hot spring water is alkaline and silky smooth. Locals call it "bijin no yu" (beauty bath) and claim it\'s why the women of Bessho have had famously beautiful skin for a thousand years.',
    year: 800,
    color: '#FF7043',
    related: ['anrakuji', 'ueda-castle'],
    wiki: 'Bessho_Onsen',
  },
  {
    id: 'anrakuji',
    lat: 36.3590, lng: 138.1800,
    title: '安楽寺 八角三重塔',
    titleEn: 'Anraku-ji Octagonal Pagoda',
    desc: 'The only octagonal three-story pagoda in Japan — a National Treasure.',
    history: 'Anraku-ji temple was founded in the Nara period (710–794), but its crowning glory is the octagonal three-story pagoda built around 1290 during the Kamakura period. It is the only structure of its kind in Japan and was designated a National Treasure. The pagoda\'s design shows Song Dynasty Chinese influence, reflecting the deep cultural exchange of that era. The temple belongs to the Sōtō Zen school.',
    funFact: 'For centuries people counted it as a "two-story" pagoda because the bottom level is hidden by the hillside. It wasn\'t officially recognized as three stories until modern architectural surveys.',
    year: 1290,
    color: '#4CAF50',
    related: ['bessho-onsen', 'ueda-castle'],
    wiki: 'Anraku-ji',
  },
  // === Further east — toward Karuizawa / Asama foothills ===
  {
    id: 'onioshidashi',
    lat: 36.4400, lng: 138.5400,
    title: '鬼押出し園',
    titleEn: 'Onioshidashi Lava Park',
    desc: 'Otherworldly lava field from Mount Asama\'s catastrophic 1783 eruption.',
    history: 'When Mount Asama erupted in 1783 (Tenmei eruption), a massive pyroclastic flow poured down the north slope, burying Kambara village and killing over 1,500 people. The lava cooled into bizarre twisted formations stretching across the mountainside. The park was opened in 1930 to preserve this volcanic landscape. A Kannon temple sits atop the lava field, built to comfort the spirits of the victims.',
    funFact: 'The name means "demons pushed it out" — locals believed the twisted lava rocks were boulders hurled by oni (demons) living inside the volcano.',
    year: 1783,
    color: '#D32F2F',
    related: ['asama', 'takamine', 'kori-fuketsu'],
    wiki: 'Onioshidashi',
  },
  {
    id: 'mikasa-hotel',
    lat: 36.3580, lng: 138.5850,
    title: '旧三笠ホテル',
    titleEn: 'Mikasa Hotel (Historic)',
    desc: 'Meiji-era Western-style hotel, an Important Cultural Property of Japan.',
    history: 'Built in 1906 by Yamamoto Naosuke, the Mikasa Hotel was one of Japan\'s first purely Western-style resort hotels. It hosted politicians, intellectuals, and aristocrats escaping Tokyo\'s summer heat. The wooden building features elegant colonial architecture and was designated an Important Cultural Property in 1980. It earned the nickname "Karuizawa no Rokumeikan" after Tokyo\'s famous Western ballroom.',
    funFact: 'The hotel had Japan\'s first commercial electric lights outside Tokyo. Guests from 1906 could enjoy electric lamps while the rest of rural Nagano used oil lanterns.',
    year: 1906,
    color: '#7B1FA2',
    related: ['onio-pass', 'komoro-station'],
    wiki: 'Karuizawa',
  },
  {
    id: 'kumano-shrine',
    lat: 36.3420, lng: 138.5530,
    title: '熊野皇大神社',
    titleEn: 'Kumano Kōtai Shrine',
    desc: 'Ancient shrine straddling the Nagano-Gunma border on Usui Pass.',
    history: 'Founded according to legend by Yamato Takeru in 110 AD, this shrine sits exactly on the provincial border at the summit of Usui Pass. The main hall is split — the left side is in Nagano Prefecture, the right side in Gunma. For centuries, travelers on the Nakasendo highway stopped here to pray for safe passage over the treacherous mountain crossing.',
    funFact: 'The shrine has two separate religious corporations — one registered in Nagano, one in Gunma. New Year\'s donations from the left pocket go to Nagano, right pocket to Gunma.',
    year: 110,
    color: '#C62828',
    related: ['onio-pass', 'mikasa-hotel'],
    wiki: 'Usui_Pass',
  },
  {
    id: 'shiraito-falls',
    lat: 36.3830, lng: 138.5680,
    title: '白糸の滝',
    titleEn: 'Shiraito Falls',
    desc: 'Curtain waterfall fed by underground springs from Mount Asama\'s lava.',
    history: 'The falls are 3 meters tall and 70 meters wide, creating a curtain of white threads (shiraito) as groundwater filtered through Asama\'s volcanic rock emerges from the cliff face. The water takes approximately 6 years to filter down from the mountain. The falls became a popular destination during the Taishō era (1912–1926) as Karuizawa developed as a resort area.',
    funFact: 'The water you see falling today fell as rain on Mount Asama six years ago. It\'s basically the volcano\'s very slow coffee drip system.',
    year: 1912,
    color: '#0097A7',
    related: ['asama', 'onioshidashi', 'mikasa-hotel'],
    wiki: 'Shiraito_Falls_(Nagano)',
  },
];

export function getRelatedPois(poiId) {
  const poi = POIS.find((p) => p.id === poiId);
  if (!poi) return [];
  return poi.related.map((id) => POIS.find((p) => p.id === id)).filter(Boolean);
}
